#!/usr/bin/env python3
"""Recalibrate WL buy zones to Aug 12 structure. Zones anchored on SMA50/SMA100
confluence; stops below the pre-breakout base."""
import re, sys, os, shutil

FILE = 'templates/index.html'
shutil.copy(FILE, FILE + '.bak')
src = open(FILE, 'r').read()

NEW_WL = """const WL = [
  {ticker:'MSFT', company:'Microsoft Corporation',   tier:'AI Backbone',            tc:'t1', entry:'$410&ndash;$438', target:'$625', stop:'$385',  catalyst:'Azure Q4 blowout Jul 30 &mdash; 15.5% single-session earnings gap; 20M Copilot enterprise seats; Wedbush PT $625', note:'ZONE REDRAWN Aug 13: old zone $393&ndash;412 was cleared by the Jul 30 earnings gap ($390.54 close &rarr; $451.10). New zone $410&ndash;438 = the rising SMA50 ($410.30) up to the first post-gap consolidation shelf. Stop $385 sits just below the gap origin $390.54 &mdash; a full gap-fill would mean the Azure re-rating is being unwound, not merely digested. Current $492.43 is 20% above SMA50: extended, no entry. R/R from $424 mid: 5.2:1'},
  {ticker:'NVDA', company:'NVIDIA Corporation',      tier:'AI Infrastructure',       tc:'t2', entry:'$203&ndash;$213', target:'$300', stop:'$192',  catalyst:'Blackwell GB300 ramp; $500B revenue visibility; cleanest SMA stack on the board (50 &gt; 100, both rising)', note:'ZONE REDRAWN Aug 13: old zone $175&ndash;192 is 15% below market and no longer reachable without a thesis break. New zone $203&ndash;213 = the SMA100 $203.20 / SMA50 $206.13 confluence, which is now the first real support shelf. Stop $192 = the old zone top, which flipped from resistance to support during the July run. Current $224.09 above zone. R/R from $208 mid: 5.8:1'},
  {ticker:'ORCL', company:'Oracle Corporation',      tier:'Long-Term Hold',          tc:'t1', entry:'$138&ndash;$150', target:'$215', stop:'$128',  catalyst:'AI cloud RPO $553B; OCI +84% YoY; recovered +21% off the lows but has not reclaimed its trend filter', note:'ZONE REDRAWN Aug 13: old zone $165&ndash;182 was never reached &mdash; ORCL fell straight through to $126 and has only recovered to $153. New zone $138&ndash;150 reflects where the stock actually based. Stop $128 = below the Jul low. CRITICAL: SMA50 $155.58 is still FALLING and price sits beneath it, so the SMA gate blocks entry even inside the zone. Requires an SMA50 reclaim first. R/R from $144 mid: 4.4:1'},
  {ticker:'AMD',  company:'Advanced Micro Devices',  tier:'Primary Pick',            tc:'t2', entry:'$440&ndash;$470', target:'$600', stop:'$415',  catalyst:'MI400 Helios racks shipping; $60B hyperscaler commits from OpenAI and Meta; only large AI name still below its SMA50', note:'ZONE REDRAWN Aug 13: old zone $370&ndash;390 is far below market and was never tagged. New zone $440&ndash;470 sits beneath the falling SMA50 $511.56 &mdash; deliberately, because AMD is the one large AI name still under its trend filter after a &minus;2.6% four-week stretch while peers ran 10&ndash;29%. Stop $415 = below the Jul consolidation. Entry requires an SMA50 reclaim, not just a zone tag. R/R from $455 mid: 3.6:1'},
  {ticker:'LMND', company:'Lemonade Inc.',            tier:'AI Disruption',           tc:'t2', entry:'$45&ndash;$56',   target:'$88',  stop:'$38',   catalyst:'Tesla FSD autonomous insurance AZ+OR LIVE; Q4 2026 EBITDA target; 6% LAE vs industry 8&ndash;10%', note:'ZONE UNCHANGED &mdash; and LMND is now the ONLY watchlist name inside its buy zone at $51.64 after falling 23% from $67. But the SMA gate BLOCKS: SMA50 $60.04 is falling and price is $8.40 beneath it. This is the textbook falling-knife structure the filter exists to catch (see ORCL &minus;30%). Zone presence alone is not a setup. Watch for a base above $52 plus an SMA50 flattening &mdash; that would make LMND the first genuine new entry in weeks. R/R from $50 mid: 3.2:1'},
  {ticker:'DELL', company:'Dell Technologies Inc',   tier:'AI Server Assembly',      tc:'t2', entry:'$418&ndash;$448', target:'$600', stop:'$392',  catalyst:'AI server revenue +757% YoY; record $51.3B backlog; fully recovered from the Jun drawdown, +22% in four weeks', note:'ZONE REDRAWN Aug 13 (second redraw): the Jun 11 zone $335&ndash;355 did its job &mdash; DELL based there and has since run to $484.50. New zone $418&ndash;448 anchors on the rising SMA50 $418.69. Stop $392 = below the Aug breakout base. SMA100 $320.36 is far below, confirming a strong, well-established trend. Current price above zone. R/R from $433 mid: 4.1:1'},
  {ticker:'PANW', company:'Palo Alto Networks',      tier:'AI Security',             tc:'t1', entry:'$322&ndash;$350', target:'$460', stop:'$300',  catalyst:'NGS ARR +60% YoY; XSIAM SOC consolidation; steadiest climber on the board &mdash; SMA50 rising sharply from $258 to $322', note:'ZONE REDRAWN Aug 13: old zone $232&ndash;252 is 35% below market. New zone $322&ndash;350 anchors on the rising SMA50 $322.21. Stop $300 = round-number support below the SMA50 and beneath the Jul base. The SMA50/SMA100 spread ($322 vs $258) is the widest on the watchlist &mdash; a very strong trend, but it also means price is 20% above its own filter and extended. R/R from $336 mid: 3.4:1'},
  {ticker:'PLTR', company:'Palantir Technologies',   tier:'AI Operating System',     tc:'t1', entry:'$138&ndash;$152', target:'$220', stop:'$125',  catalyst:'85% YoY revenue growth; $7.65B FY2026 guide; DIA contract pending; biggest four-week move on the board at +29%', note:'ZONE REDRAWN Aug 13: old zone $108&ndash;122 is 30% below market. New zone $138&ndash;152 spans the SMA50 $133.89 / SMA100 $137.89 confluence. Stop $125 = below both moving averages and below the Jul base. Current $171.04 is 28% above the SMA50 &mdash; the most extended name on the watchlist. Momentum is real but the entry window is long closed. Do not chase. R/R from $145 mid: 3.75:1'},
  {ticker:'VRT',  company:'Vertiv Holdings Co',      tier:'AI Infrastructure Hardware &#9888; BROKEN', tc:'t2', entry:'$255&ndash;$275', target:'$420', stop:'$240',  catalyst:'Order backlog $15B (+109% YoY); BofA PT $440 &mdash; but thesis is on hold pending price repair', note:'ZONE BROKEN Aug 13: VRT fell THROUGH its $290 floor and closed $288.36, with SMA50 $298.32 and SMA100 $303.38 both above price and falling. This is the exact structure ORCL showed before it fell 30%. Damning detail: VRT went &minus;0.4% over four weeks while every AI-infrastructure peer ran 10&ndash;29% &mdash; relative weakness during a sector melt-up is a real signal, not noise. New zone $255&ndash;275 marks the next structural base below the break. ENTRY REQUIRES BOTH a stabilization base AND an SMA50 reclaim &mdash; do not average into a broken zone. R/R from $265 mid: 6.2:1 (on paper only until structure repairs)'},
  {ticker:'ANET', company:'Arista Networks Inc',     tier:'AI Networking',           tc:'t1', entry:'$172&ndash;$190', target:'$265', stop:'$158',  catalyst:'FY2026 guide $11.5B (+28%); $3.5B AI fabric revenue; Ultra Ethernet Consortium leader; +25% in four weeks', note:'ZONE REDRAWN Aug 13: old zone $128&ndash;148 is 30% below market. New zone $172&ndash;190 anchors on the rising SMA50 $172.58. Stop $158 = below the SMA50 and beneath the Jul breakout base, above the SMA100 $161.06. The supply-chain friction flagged in the spring has not derailed the trend. Current $210.50 above zone. R/R from $181 mid: 3.7:1'},
  {ticker:'AVGO', company:'Broadcom Inc',            tier:'AI Custom Silicon',       tc:'t2', entry:'$390&ndash;$408', target:'$550', stop:'$368',  catalyst:'Q1 AI rev $8.4B (+106% YoY); CEO Hock Tan $100B AI revenue by 2027; $73B backlog with 18-month runway', note:'ZONE REDRAWN Aug 13 (second redraw): the $350&ndash;375 zone was tagged in Jul and AVGO has since recovered to $416.05. New zone $390&ndash;408 sits on the unusually tight SMA50 $393.47 / SMA100 $390.98 confluence &mdash; the two averages nearly on top of each other, forming a well-defined support shelf. Stop $368 = below the Jul low $370.83. SMA50 is roughly flat rather than clearly rising, so this is the weakest trend among the gate-passers. R/R from $399 mid: 4.9:1'},
  {ticker:'NOW',  company:'ServiceNow Inc',          tier:'AI Enterprise Control Plane &#9733; OPEN +21%', tc:'t1', entry:'$112&ndash;$122', target:'$175', stop:'$103',  catalyst:'AI Control Tower + Otto agent; Experian agentic partnership; cleared SMA200 $122.44 &mdash; uptrend confirmed', note:'ACTIVE POSITION &mdash; POTW winner, entered $103.24 (Jul 19&ndash;25), now $124.94 for +21.0%. TRAIL STOP RAISED $88 &rarr; $113 (2x ATR of $5.95), locking +9.5%. ZONE REDRAWN for new money only: $112&ndash;122 spans the SMA150 $107.83 up to the SMA200 $122.44, which flipped from resistance to support on the breakout. Price is now above ALL FOUR moving averages (50 $107.59, 100 $102.84, 150 $107.83, 200 $122.44) for the first time this cycle &mdash; the milestone that ends the inverted-stack caveat. Target $175 still 40% away. R/R from $117 mid: 4.1:1'},
  {ticker:'MRVL', company:'Marvell Technology Inc',  tier:'AI Custom Silicon',       tc:'t2', entry:'$195&ndash;$215', target:'$310', stop:'$182',  catalyst:'AWS Trainium3 + Google TPU custom silicon; AI networking ASIC revenue +87% YoY; recovered +15% off the $189 low', note:'ZONE REDRAWN Aug 13: old zone $220&ndash;242 sat above the actual base. MRVL bottomed at $188.68 and has recovered to $217.08. New zone $195&ndash;215 anchors on the SMA100 $195.12 and the recovery base. Stop $182 = below the Jul low. GATE STILL BLOCKS: SMA50 $240.97 remains ABOVE price &mdash; MRVL is recovering, not recovered. The trail stop that exited this position at $272 avoided a further 35% of downside; do not re-enter until price reclaims the SMA50. R/R from $205 mid: 4.6:1'},
];"""

pattern = r'const WL = \[.*?\n\];'
new_src, count = re.subn(pattern, lambda m: NEW_WL, src, flags=re.DOTALL)

if count != 1:
    print(f'ERROR: expected 1 replacement, got {count}')
    sys.exit(1)

open(FILE, 'w').write(new_src)
print(f'OK - replaced WL block ({count} substitution)')
os.remove(FILE + '.bak')
print('Cleaned up backup file')
