#!/usr/bin/env python3
"""MONITOR_DATA -> Sep 4."""
import re, sys, os, shutil
FILE='templates/index.html'; shutil.copy(FILE,FILE+'.bak'); src=open(FILE).read()

U={
'ANET':('OPEN POSITION - GATE HOLDING','POTW OPEN +4.1% - STOP $178','vd-strong',
 'Call Up - Sep 5, 2026 (POTW GRADE): ANET $193.77, up 4.12% from the $186.10 entry called two sessions ago. The gate that justified the trade is intact - SMA50 has kept rising to $182.88 with price comfortably above it, and the full stack remains in bullish order. THE HONEST CALIBRATION: ATR(14) is $7.81, which is 4.03% of price. The entire +4.12% gain therefore equals 0.98x ATR - slightly LESS than one average day of range. Two sessions of movement inside a single ATR is not evidence of anything, and calling this a win at day two would be reading noise as signal. The correct statement is that the thesis is intact and the trade is working, not that it is proven. Judge it at 2-3x ATR. ACTION TAKEN: stop raised $170 to $178, which is 2x ATR below current price and sits beneath the rising SMA50 so ordinary tests of the average will not trigger it. Risk from entry drops from $16.10 to $8.10 per share; R/R from $193.77 is 4.52:1. The entry window is closed - price is above the $190 zone top, so this is a management position and not an entry. Watch $182.88: a close beneath the SMA50 breaks the gate and warns roughly $5 before the stop.'),

'NOW': ('CONFIRMED - TRAIL UNTOUCHED','OPEN +36.8% - TRAIL $124','vd-strong',
 'Call Up - Sep 5, 2026: NOW $141.27, now +36.8% from the $103.24 zone-floor entry, after touching $145.59 on Sep 3. SMA50 $117.11 continues rising steeply with price $24 above it. The $124 trail set on Sep 3 has not been approached - it sits $17 beneath price. Nothing to do this session. Target $175 is 24% away. This position has now been managed across three consecutive call ups with the trail raised twice ($88 to $113 to $124) and never tested, which is what a working trend position looks like: the work is in not interfering with it.'),

'DELL':('INTACT - FLAT-SMA CAUTION RESOLVED UP','ABOVE ZONE - GATE PASS RESTORED','vd-caution',
 'Call Up - Sep 5, 2026 (FLAG RESOLVED): DELL $523.93, up 6.4%. On Sep 3 DELL was flagged with a caution because its SMA50 had gone flat ($434.10, $434.22, $434.17 across three sessions) and the AVGO precedent held that a flat average is the absence of trend rather than a milder uptrend. That average has now turned decisively back UP to $439.30 and the stock gained 6.4%. RECORDING THIS PLAINLY: the caution was warranted on the evidence available at the time, and the outcome went the other way. A flat SMA50 is genuinely ambiguous - it resolves upward about as often as downward - which is precisely why it justifies watching rather than acting or exiting. The contrast with AVGO, which was flagged for the same reason and has since kept falling, is the useful part: same signal, opposite resolutions. DELL returns to an unqualified gate pass. AI server revenue +757% YoY and the $51.3B backlog unchanged.'),

'ORCL':('REPAIRED - BUT THE ZONE IS GONE','ZONE CLEARED - EARNINGS THU SEP 10','vd-caution',
 'Call Up - Sep 5, 2026 (SEQUENCING LESSON): ORCL $158.77, up 8.9%. The Sep 3 note asked specifically to watch for the SMA50 to flatten as step two of trend repair. It has: the average went $139.78, $139.71, then TICKED UP to $139.74. Step two is complete. But price ran 8.9% in the same two sessions and cleared the $138-150 zone entirely - the structure qualified only after the entry had gone. THIS IS NOT A FRAMEWORK FAILURE; it is the cost of requiring two independent conditions that can resolve in either order. Worth logging as a pattern: when a name is one condition away from qualifying AND is deeply oversold, the zone can vanish faster than the trend repairs. EARNINGS THU SEP 10 (Q1 FY2027, est. EPS $1.67). Guidance calls for 58-64% cloud growth - that is the bar. RBC flags execution risk on the layoff-funded AI infrastructure buildout; Jefferies cut its target to $290 from $320; Morgan Stanley holds Equalweight at $210. EU regulators are reviewing cloud licensing practices. Any entry now is an earnings bet rather than a technical one. Stand aside through the print.'),

'VRT': ('BROKEN - BUT NEAREST TO RECLAIM','$1.94 UNDER SMA50 - WATCH','vd-caution',
 'Call Up - Sep 5, 2026: VRT $280.52, up 9.3% - the biggest bounce on the board - and now just $1.94 beneath its SMA50 $282.46. That is the closest VRT has come to reclaiming its trend filter since the breakdown, and a single good session flips it. THE CAUTION: this was a Fed rate-hold bounce, which re-prices duration rather than repairing a downtrend. The SMA50 is still falling and price is still under it, so nothing has changed structurally yet. The entry conditions attached to the redrawn zone are unchanged and both still required: a stabilization base AND an SMA50 reclaim. VRT has neither confirmed. Upgrading this from broken to watch would require the reclaim to hold for several sessions with the average flattening. Watch closely, do not anticipate. Backlog $15B (+109% YoY) unchanged throughout.'),

'AVGO':('BROKEN - WEAKEST STRUCTURE, THIRD CALL UP','ONLY DECLINER IN A RISK-ON BOUNCE','vd-exit',
 'Call Up - Sep 5, 2026 (CLEAREST AVOID): AVGO $357.87, DOWN 2.6% - the only watchlist name that fell during a broad risk-on bounce in which the most beaten-down names rallied 8-9%. SMA50 $383.65 continues falling with price $26 beneath it. This is the THIRD consecutive call up in which AVGO has been the weakest structure on the board, and it has now broken two zone floors in this cycle. FAILING TO PARTICIPATE IN A RALLY THAT LIFTED EVERYTHING ELSE is the single clearest relative-weakness signal available - it is the same read that preceded VRT falling 27%, and VRT at least bounced this time while AVGO did not. The business case (Q1 AI revenue $8.4B +106% YoY, $73B backlog, Hock Tan targeting $100B by 2027) has never been the issue; the price structure is, and it is deteriorating rather than stabilising. No entry, no averaging down, no exceptions.'),

'MSFT':('INTACT - ZONE CLOSED BY ITS OWN FILTER','ABOVE ZONE - $500','vd-caution',
 'Call Up - Sep 5, 2026: MSFT $499.68 (+0.6%), quiet through both the pullback and the bounce. The structural development worth recording: SMA50 has risen to $444.38 and has now climbed THROUGH the old zone top of $438. The $410-438 zone no longer exists as a reachable structure - any future pullback would meet the rising average before reaching the zone, so the zone needs redrawing at the next full refresh. The Jul 30 Azure gap (+15.5% in one session, blocked by the gate at $394) remains the largest single winner the SMA filter has cost, and the case for a pre-earnings exception still stands.'),

'NVDA':('INTACT - HELD BOTH DIRECTIONS','ABOVE ZONE - CLEANEST STRUCTURE','vd-caution',
 'Call Up - Sep 5, 2026: NVDA $230.35 (+2.6%). Notable for what it did NOT do: it held up during the three-week pullback that took six names into their zones, then participated in the bounce. It is the only name on the board to manage both without drama. SMA50 $210.53 rising, SMA100 beneath it, price above both - this remains the cleanest structure on the watchlist. Zone $203-213 now sits 8% below market. No entry available; the pullback that reached six other names simply never reached NVDA, which is itself the argument for its quality.'),

'PLTR':('INTACT - EXTENSION RESOLVING','ABOVE ZONE - GAP CLOSING','vd-caution',
 'Call Up - Sep 5, 2026: PLTR $174.31 (+2.9%). The extension flagged in mid-August continues to resolve the healthy way - through time rather than through a drawdown. SMA50 has risen to $150.05, narrowing the gap from 28% above the average in August to 16% now, while price has held. The SMA50 is now inside the $138-152 zone, meaning a routine pullback would meet both at once - a materially cleaner test than existed a month ago. Still above zone, still no entry, but converging rather than deteriorating.'),

'PANW':('UNRESOLVED - BARELY BOUNCED','IN ZONE - $16 UNDER RISING SMA50','vd-caution',
 'Call Up - Sep 5, 2026: PANW $333.22, up only 1.4% while beaten-down peers gained 8-9%. That underparticipation is itself a mild negative in a rate-relief bounce, where the most-sold-off names should lead. Still inside zone $322-350 but $16 beneath a still-RISING SMA50 $349.28 - the fresh-breakdown structure is unchanged from Sep 3. The resolution window remains open in both directions: reclaim $349 and PANW becomes a strong second setup with the stack intact; roll the SMA50 over and it joins AVGO and VRT in the broken column. NGS ARR +60% YoY and the XSIAM platformization thesis unchanged - nothing in the business has broken.'),

'AMD': ('INTACT - ZONE TAGGED AND LEFT AGAIN','LEFT ZONE - STILL UNDER SMA50','vd-caution',
 'Call Up - Sep 5, 2026: AMD $477.45, up 4.5%, and has now bounced back OUT of the $440-470 zone it entered on Sep 2 - without ever passing the gate while inside it. SMA50 $498.85 is still falling with price $21 beneath. This is the second time the zone has been tagged and left unfilled, which is exactly what the zone was designed to do: it was deliberately set beneath the falling SMA50 so a zone tag alone could not trigger an entry. The requirement is unchanged and has not moved - the SMA50 reclaim, not the zone tag. MI400 Helios thesis intact with $60B committed from OpenAI and Meta.'),

'LMND':('INTACT - SMA50 HAS NEARLY STOPPED FALLING','IN ZONE 4TH TIME - CLOSEST YET','vd-caution',
 'Call Up - Sep 5, 2026 (CLOSEST YET): LMND $53.40, inside zone $45-56 for the FOURTH consecutive call up. The development: the SMA50 fell just $0.02 on the day ($58.82 to $58.81) - effectively flat after months of steady decline. Price has now based above $52 across four call ups. THE TRIGGER HAS BEEN STATED IDENTICALLY EVERY TIME: a base holding above $52 PLUS a flattening SMA50. The first half has held for a month and the second half is now arriving. This is the closest LMND has been to actionable since it entered the zone. It is still not there - price remains $5.41 beneath the average, so the gate holds and there is no entry. But the consistency of the answer across four sessions, and the fact that the stock is finally meeting the stated condition rather than the condition being relaxed, is the framework working as intended. Tesla FSD insurance live in AZ and OR; Q4 EBITDA target unchanged.'),
}
n=0
for tk,(th,vd,vc,al) in U.items():
    esc=lambda s: s.replace('\\','\\\\').replace("'","\\'")
    rep=("    thesis:'"+esc(th)+"', verdict:'"+esc(vd)+"', verdictCls:'"+vc+"',\n    alert:'"+esc(al)+"',\n")
    pat=(r"(\n  "+tk+r": \{.*?)"
         r"\n    thesis:'(?:[^'\\]|\\.)*', verdict:'(?:[^'\\]|\\.)*', verdictCls:'[^']*',"
         r"\n    alert:'(?:[^'\\]|\\.)*',\n")
    src,k=re.subn(pat, lambda m:m.group(1)+"\n"+rep, src, flags=re.DOTALL)
    if k!=1: print(f'ERROR {tk}: {k}'); sys.exit(1)
    n+=1
open(FILE,'w').write(src); print(f'OK - {n} monitor entries refreshed'); os.remove(FILE+'.bak')
