#!/usr/bin/env python3
"""WL notes -> Sep 4. ANET stop 170->178. Zones unchanged (set Sep 3)."""
import re, sys, os, shutil
FILE='templates/index.html'; shutil.copy(FILE,FILE+'.bak'); src=open(FILE).read()

UP = {
'ANET': ('$178', 'OPEN POSITION &mdash; POTW +4.1%. Entered $186.10 Sep 3, closed Sep 4 at $193.77. Gate intact: SMA50 risen to $182.88, price above. CALIBRATION: ATR(14) $7.81 = 4.03% of price, so the +4.12% gain equals 0.98x ATR &mdash; under one average day of range. Working, not yet proven; judge at 2&ndash;3x ATR. STOP RAISED $170 &rarr; $178 (2x ATR below price, beneath the rising SMA50 so ordinary tests do not trigger it), cutting entry risk $16.10 &rarr; $8.10. R/R from $193.77: 4.52:1. Price is above the $190 zone top &mdash; entry window closed, this is management only.'),
'NOW':  (None, 'OPEN POSITION &mdash; +36.8% from the $103.24 entry. $141.27 on Sep 4 after touching $145.59 Sep 3. SMA50 $117.11 rising steeply, price $24 above it. Trail $124 untouched and $17 beneath price. Target $175 remains 24% away. Nothing to do &mdash; the trail was raised Sep 3 and the position has not approached it.'),
'ORCL': (None, 'ZONE GONE, STRUCTURE ARRIVED LATE. The Sep 3 note asked to watch for the SMA50 to flatten &mdash; it did: $139.78, $139.71, then TICKED UP to $139.74. Step two of trend repair complete. But price ran 8.9% to $158.77 in the same two sessions and cleared the $138&ndash;150 zone entirely. The structure qualified only after the entry was gone. EARNINGS THU SEP 10 (Q1 FY2027, est. EPS $1.67; guidance bar is 58&ndash;64% cloud growth). Any entry now is an earnings bet, not a technical one. RBC flags execution risk on the layoff-funded AI buildout; Jefferies cut to $290 from $320; Morgan Stanley Equalweight $210. Stand aside through the print.'),
'VRT':  (None, 'CLOSEST TO RECLAIM SINCE THE BREAKDOWN. VRT bounced 9.3% to $280.52 &mdash; the biggest move on the board &mdash; and now sits just $1.94 beneath its SMA50 $282.46. One good session flips the trend filter. But the average is still falling and price is still under it, so the gate blocks and nothing has changed structurally yet. Note what drove it: a Fed rate-hold hint, which re-prices duration rather than repairing a downtrend. Entry still requires BOTH a base AND the SMA50 reclaim. Watch closely &mdash; do not anticipate.'),
'MRVL': (None, 'RECLAIMED THE SMA50 &mdash; STEP ONE OF THREE. MRVL bounced 8.2% to $223.50, back above SMA50 $220.37 for the first time since the stop-out. But that average is still FALLING, so this is the same position ORCL was in three weeks ago: reclaim done, flatten and rise still pending. Price has also left the $195&ndash;215 zone. Not a setup. The trail that exited at $272 has still avoided roughly 18% of downside at current prices.'),
'AMD':  (None, 'BOUNCED OUT OF THE ZONE WITHOUT QUALIFYING. AMD rose 4.5% to $477.45, leaving the $440&ndash;470 zone it entered on Sep 2 &mdash; without ever passing the gate while inside it. SMA50 $498.85 is still falling with price $21 beneath. This is the second time the zone has been tagged and left unfilled. Unchanged requirement: the SMA50 reclaim, not the zone tag. MI400 thesis intact.'),
'DELL': (None, 'FLAT-SMA50 CAUTION RESOLVED UPWARD &mdash; recorded plainly. DELL was flagged Sep 3 because its SMA50 had gone flat ($434.10 / $434.22 / $434.17) and the AVGO precedent said a flat average is the absence of trend. The average turned decisively back UP to $439.30 and DELL gained 6.4% to $523.93. The caution was warranted on the evidence available and the outcome went the other way. A flat SMA50 is genuinely ambiguous &mdash; it resolves up about as often as down &mdash; which is why it justifies watching rather than acting. Back to an unqualified gate pass. Above zone $418&ndash;448.'),
'AVGO': (None, 'THE ONLY NAME DOWN IN A BROAD RISK-ON BOUNCE. Every other watchlist name rose; AVGO fell 2.6% to $357.87 while the most beaten-down names around it rallied 8&ndash;9%. SMA50 $383.65 still falling, price $26 beneath it. This is the THIRD consecutive call up with AVGO as the weakest structure on the board, and it has broken two zone floors this cycle. Non-participation in a rally that lifted everything else is the same relative-weakness signal that preceded VRT falling 27%. No entry, no averaging down, no exceptions.'),
'PANW': (None, 'UNCHANGED NEAR-MISS &mdash; and it barely bounced. PANW rose just 1.4% to $333.22 while beaten-down peers gained 8&ndash;9%, which is itself a mild negative. Still inside zone $322&ndash;350 but $16 beneath a RISING SMA50 $349.28 &mdash; the fresh-breakdown structure is identical to Sep 3. The resolution window is still open: reclaim $349 and it becomes a strong second setup; roll the SMA50 over and it joins the broken column.'),
'LMND': (None, 'FOURTH CONSECUTIVE CALL UP IN ZONE &mdash; and the SMA50 has nearly stopped falling. LMND $53.40, inside zone $45&ndash;56. The SMA50 fell just $0.02 on the day ($58.82 &rarr; $58.81) &mdash; effectively flat after months of decline. Price has now based above $52 across four call ups. The stated trigger has been identical each time: a base above $52 PLUS a flattening SMA50. The first half has held and the second half is arriving. This is the closest LMND has been to actionable &mdash; but price is still $5.41 beneath the average, so the gate holds.'),
'MSFT': (None, 'ZONE NOW FULLY CLOSED BY ITS OWN TREND FILTER. MSFT $499.68 (+0.6%). SMA50 has risen to $444.38 &mdash; it has now climbed THROUGH the old zone top $438, so the $410&ndash;438 zone no longer exists as a reachable structure; any pullback would meet the rising average first. Worth noting for the next redraw. The Jul 30 Azure gap remains the largest winner the SMA gate has cost.'),
'NVDA': (None, 'CLEANEST STRUCTURE, MAINTAINED THROUGH BOTH DIRECTIONS. NVDA $230.35 (+2.6%) held up during the three-week pullback and participated in the bounce &mdash; the only name to do both without drama. SMA50 $210.53 rising, price above. Zone $203&ndash;213 now 8% below market. No entry; the pullback that reached six other names never reached NVDA.'),
'PLTR': (None, 'EXTENSION GAP STILL CLOSING THROUGH TIME. PLTR $174.31 (+2.9%). SMA50 has risen to $150.05, narrowing the gap to 16% above the average, down from 28% in mid-August &mdash; the healthy way for an extended name to resolve. Zone $138&ndash;152 with the SMA50 now inside it. Still above zone, still no entry, but the setup is converging rather than deteriorating.'),
}
for tk,(stop,note) in UP.items():
    m = re.search(r"\{ticker:'"+tk+r"',.*?\n", src)
    if not m: print(f'ERROR: {tk}'); sys.exit(1)
    line=m.group(0)
    new = re.sub(r"note:'(?:[^'\\]|\\.)*'\}", "note:'"+note.replace('\\','\\\\').replace("'","\\'")+"'}", line)
    if stop: new = re.sub(r"stop:'[^']*'", "stop:'"+stop+"'", new)
    if new==line: print(f'ERROR: {tk} unchanged'); sys.exit(1)
    src = src.replace(line,new,1); print(f'  {tk}'+(f' (stop {stop})' if stop else ''))
open(FILE,'w').write(src); print('OK - WL refreshed'); os.remove(FILE+'.bak')
