#!/usr/bin/env python3
"""WL: refresh notes to Sep 2 status. Zones from Aug 13 mostly hold; ANET stop
tightened to the 2xATR/SMA100/zone-floor confluence, AVGO marked broken."""
import re, sys, os, shutil
FILE='templates/index.html'; shutil.copy(FILE,FILE+'.bak'); src=open(FILE).read()

# (ticker, new stop or None to keep, new note)
UP = {
'ANET': ('$170', 'ACTIVE SETUP &mdash; PLAY OF THE WEEK Sep 3&ndash;11. ANET fell 11.6% to $186.10, into zone $172&ndash;190, and is the ONLY name of the seven now in zones that passes the SMA gate. PERFECT BULLISH STACK: SMA50 $181.83 &gt; SMA100 $170.62 &gt; SMA150 $158.55 &gt; SMA200 $151.32, all beneath price, SMA50 rising. STOP TIGHTENED $158 &rarr; $170 on a triple confluence: 2x ATR ($7.81) below price = $170.47, the SMA100 $170.62, and just under the zone floor $172. R/R at $186.10: $78.90 up / $16.10 down = 4.90:1. Entry still requires volume &ge;1.5x the 20-day average. No earnings in the window.'),
'NOW':  ('$124', 'ACTIVE POSITION &mdash; +32.4% open from the $103.24 zone-floor entry (Jul 19&ndash;25 POTW). $136.72 on Sep 2 after adding 9.4% while SPY fell 0.9% and QQQ fell 2.0% &mdash; the strongest relative-strength reading on the board. TRAIL RAISED AGAIN $113 &rarr; $124 (2x ATR of $6.09), locking +20.1%. SMA50 $115.07 rising steeply, price $21 above it. Remaining R/R to $175: 3.0:1. Zone $112&ndash;122 is for new money only and price is now above it &mdash; no adds.'),
'AVGO': ('$340', 'ZONE BROKEN Sep 3 &mdash; SECOND BREAK THIS CYCLE. AVGO fell 11.7% to $367.24, beneath the $390&ndash;408 zone redrawn only three weeks earlier, with SMA50 $384.58 falling and price $17 under it. The Aug 13 note flagged AVGO as the weakest gate pass specifically because its SMA50 was FLAT rather than rising &mdash; that caution was correct. A flat SMA50 is the absence of trend, not a milder version of an uptrend. Stop lowered to $340 below the current structure. Joins VRT in the broken column: base plus SMA50 reclaim required before this is tradeable. No averaging down.'),
'PANW': (None, 'NEAR-MISS Sep 3 &mdash; the most interesting block on the board. PANW fell 15.1% to $328.48, the biggest decliner, and sits INSIDE zone $322&ndash;350 &mdash; but $20 beneath a still-RISING SMA50 $348.24. A rising average with price newly below it is a FRESH BREAKDOWN, not an established downtrend, and it resolves within a couple of weeks either way. If PANW reclaims $348 it becomes a strong second setup with the stack intact. ZS (Zscaler) reports Thu Sep 3 after the close &mdash; the cleanest read-through on whether this is sector-wide cybersecurity de-rating or PANW-specific.'),
'VRT':  (None, 'STILL BROKEN Sep 3. VRT fell another 11.0% to $256.70, reaching the $255&ndash;275 zone redrawn on Aug 13 &mdash; but the entry conditions attached to that redraw are still unmet: SMA50 $284.54 is falling and price is $28 beneath it. The zone was drawn as a target for where a base MIGHT form, not as a buy trigger. Requires BOTH a stabilization base AND an SMA50 reclaim. VRT has now fallen 27% from the Jul 17 level while the relative-weakness warning issued Aug 13 played out in full.'),
'AMD':  (None, 'IN ZONE, BLOCKED BY DESIGN Sep 3. AMD fell 5.4% to $457.06, entering the $440&ndash;470 zone &mdash; exactly as intended. That zone was deliberately set BENEATH the falling SMA50 so a zone tag alone could not trigger entry, and the design is doing its job: SMA50 $501.70 is still falling with price $45 below. AMD remains the large AI name furthest under its own trend filter. Entry requires the SMA50 reclaim, not merely the zone tag. MI400 thesis unchanged.'),
'ORCL': (None, 'PRECONDITION MET Sep 3 &mdash; closest ORCL has come. Price $145.75 is inside zone $138&ndash;150 AND has RECLAIMED the SMA50 $139.69 for the first time in months. But that average is still FALLING, so the gate holds and there is no entry. The sequence that repairs a broken trend is reclaim, then flatten, then rise &mdash; ORCL has completed step one of three. This is the name that validated the gate in the first place (&minus;30% through its zone), so the bar for re-entry is deliberately high. Watch for the SMA50 to flatten.'),
'MRVL': (None, 'IN ZONE, BLOCKED Sep 3. MRVL fell 4.9% to $206.48, inside the $195&ndash;215 zone, but SMA50 $223.26 is falling with price $17 beneath it. Unchanged verdict from Aug 13: recovering, not recovered. The trail that exited this position at $272 has now avoided a further 24% of downside. No re-entry until the SMA50 is reclaimed.'),
'LMND': (None, 'THIRD CONSECUTIVE CALL UP IN ZONE, STILL BLOCKED. LMND rose 2.9% to $53.14, inside zone $45&ndash;56 for the third call up running. SMA50 $58.83 is still falling and price is $5.69 beneath it. The knife is decelerating &mdash; the stock has stopped falling and is basing sideways &mdash; but the SMA50 has not flattened. Same trigger as before: a base above $52 plus a flattening SMA50 makes this actionable. It is closer than it was, and still not there.'),
'MSFT': (None, 'ABOVE ZONE, ZONE CLOSING FROM BELOW. MSFT $496.82 (+0.9%) held its post-gap level through the pullback. Notable mechanical detail: SMA50 has risen from $410.30 to $438.43 in three weeks and has now caught the zone TOP ($438). The $410&ndash;438 zone is being closed from beneath by its own trend filter, meaning any future pullback into the zone will arrive with the SMA50 right there &mdash; a much cleaner test than the July setup where price sat 20% above the average.'),
'NVDA': (None, 'ABOVE ZONE, TREND INTACT. NVDA $224.41 (+0.1%) was essentially flat through a pullback that took QQQ down 2.0% &mdash; quiet relative strength. SMA50 $209.15 rising, SMA100 $203.20 below it, price above both. Zone $203&ndash;213 is $11 below market and remains the cleanest structure on the watchlist. No entry; wait for the pullback that has not come.'),
'PLTR': (None, 'ABOVE ZONE, BARELY MOVED. PLTR $169.46 (&minus;0.9%) held up through the pullback despite being the most extended name on the board three weeks ago. SMA50 $147.38 rising has closed some of that gap &mdash; price is now 15% above the average versus 28% on Aug 13, so the extension is resolving through time rather than through a drawdown. Zone $138&ndash;152 below market. Still no entry.'),
'DELL': (None, 'ABOVE ZONE, BUT THE SMA50 HAS STOPPED RISING. DELL $492.20 (+1.6%) was one of only three names up over the pullback. The caution: SMA50 $434.17 has gone FLAT after weeks of steep gains. The AVGO lesson from this call up applies directly &mdash; a flat SMA50 is the absence of trend and preceded AVGO breaking its zone. Watch whether the DELL average turns up again or rolls over. Zone $418&ndash;448.'),
}

for tk,(stop,note) in UP.items():
    m = re.search(r"\{ticker:'"+tk+r"',.*?\n", src)
    if not m: print(f'ERROR: {tk} not found'); sys.exit(1)
    line = m.group(0)
    new = re.sub(r"note:'(?:[^'\\]|\\.)*'\}", "note:'"+note.replace('\\','\\\\').replace("'","\\'")+"'}", line)
    if stop:
        new = re.sub(r"stop:'[^']*'", "stop:'"+stop+"'", new)
    if new == line: print(f'ERROR: {tk} unchanged'); sys.exit(1)
    src = src.replace(line, new, 1)
    print(f'  {tk} updated' + (f' (stop -> {stop})' if stop else ''))

open(FILE,'w').write(src); print('OK - WL notes refreshed'); os.remove(FILE+'.bak')
