#!/usr/bin/env python3
"""MONITOR_DATA -> Sep 2. Preserves pp/mac/cat research; refreshes thesis/verdict/alert."""
import re, sys, os, shutil
FILE='templates/index.html'; shutil.copy(FILE,FILE+'.bak'); src=open(FILE).read()

U = {
'ANET': ('CONFIRMED - PERFECT STACK IN ZONE', 'PLAY OF THE WEEK - $186 R/R 4.90:1', 'vd-strong',
 'Call Up - Sep 3, 2026 (PLAY OF THE WEEK): ANET $186.10, down 11.6% from $210.50 over three weeks. That pullback delivered the cleanest setup the framework has produced. ANET is inside its buy zone $172-190 AND passes the SMA gate - the only one of SEVEN names currently sitting in zones to do so. THE STACK IS FLAWLESS: SMA50 $181.83 > SMA100 $170.62 > SMA150 $158.55 > SMA200 $151.32, perfect descending order, SMA50 RISING, price above all four. This matters because every prior POTW zone entry compromised somewhere - NOW at $103 was explicitly an inverted-stack, early-recovery bet that happened to return +32%. ANET is what the screen looks like when it gets exactly what it asks for. STOP $170 sits on a triple confluence: 2x ATR ($7.81) below price = $170.47, the SMA100 at $170.62, and just beneath the zone floor $172. R/R = $78.90 up to the $265 target against $16.10 of risk = 4.90:1. ENTRY GATE: Rule 4 still applies - the entry candle needs volume at or above 1.5x the 20-day average. Being in the zone is necessary, not sufficient. No watchlist earnings Sep 3-9, so this window carries trend risk only. EOS switching-cost moat and Ultra Ethernet leadership unchanged; FY2026 guide $11.5B (+28%), AI fabric revenue $3.5B.'),

'NOW':  ('CONFIRMED - RELATIVE STRENGTH LEADER', 'OPEN +32.4% - TRAIL TO $124', 'vd-strong',
 'Call Up - Sep 3, 2026: NOW $136.72, up 9.4% over three weeks IN WHICH SPY FELL 0.9% AND QQQ FELL 2.0%. That is the strongest relative-strength reading on the board and the exact mirror of the VRT warning issued Aug 13 - where VRT went flat while its sector ran and subsequently broke down. Relative performance against the tape carries information in both directions. The Jul 19-25 zone-floor entry at $103.24 is now +32.4% open. SMA50 $115.07 is rising steeply with price $21 above it. ACTION: raise the trail a second time, $113 to $124 (2x ATR of $6.09 below current price), locking in +20.1% from entry. The $113 trail set on Aug 13 was never approached. Remaining R/R to the $175 target is 3.0:1, still through the gate. NO ADDS - the entry was $103.24 and that window closed two months ago; the $112-122 zone shown on the watchlist is for new money only and price is above it. Watch $115 (SMA50) as the first warning level, well before the $124 trail.'),

'PANW': ('FRESH BREAKDOWN - NOT YET A TREND CHANGE', 'IN ZONE - $20 UNDER RISING SMA50', 'vd-caution',
 'Call Up - Sep 3, 2026 (NEAR-MISS): PANW $328.48, down 15.1% - the biggest decliner on the board, having been the steadiest climber three weeks ago. It is INSIDE zone $322-350 but sits $20 beneath a still-RISING SMA50 $348.24. This specific combination is worth understanding: a rising average with price newly below it is a FRESH BREAKDOWN, not an established downtrend, and it resolves one way or the other within a couple of weeks. Contrast AMD and VRT, where both price and the average have been falling for months. If PANW reclaims $348 with the stack still intact it becomes a strong second setup immediately. If the SMA50 rolls over, it joins the broken column. CATALYST TO WATCH: Zscaler reports Thursday Sep 3 after the close - the cleanest available read on whether this is sector-wide cybersecurity de-rating or PANW-specific. NGS ARR +60% YoY and the XSIAM platformization thesis are unchanged; nothing in the business has visibly broken.'),

'AVGO': ('BROKEN - SECOND ZONE FAILURE', 'BROKE ZONE AGAIN - MONITOR ONLY', 'vd-exit',
 'Call Up - Sep 3, 2026 (STRUCTURE BROKEN): AVGO $367.24, down 11.7% and now BELOW the $390-408 zone that was redrawn only three weeks ago. SMA50 $384.58 is falling with price $17 beneath it. This is the second time AVGO has broken through a zone floor in this cycle. THE LESSON WAS AVAILABLE IN ADVANCE: the Aug 13 call up flagged AVGO as the weakest of the eight gate passers on the specific ground that its SMA50 was FLAT rather than rising. A flat SMA50 is the absence of trend, not a milder version of an uptrend, and it deserves to be treated closer to falling than to rising. That is now a framework rule, not an observation. Stop lowered to $340 beneath current structure. AVGO joins VRT in the broken column - a base plus an SMA50 reclaim is required before it is tradeable. Business thesis (Q1 AI revenue $8.4B +106% YoY, $73B backlog, Hock Tan targeting $100B by 2027) is not the problem; price structure is.'),

'VRT':  ('BROKEN - WARNING PLAYED OUT IN FULL', 'BROKEN - BASE + RECLAIM REQUIRED', 'vd-exit',
 'Call Up - Sep 3, 2026: VRT $256.70, down another 11.0% and now 27% below the Jul 17 level. The relative-weakness warning issued Aug 13 - when VRT went -0.4% while every AI-infrastructure peer ran 10-29% - has played out completely. Price has reached the $255-275 zone redrawn at that time, but the conditions attached to that redraw remain unmet: SMA50 $284.54 is falling and price is $28 beneath it. THE ZONE WAS DRAWN AS A TARGET FOR WHERE A BASE MIGHT FORM, NOT AS A BUY TRIGGER - that distinction is the whole point of redrawing a broken zone rather than deleting it. Entry requires BOTH a stabilization base AND an SMA50 reclaim. Backlog $15B (+109% YoY) and the power-and-cooling thesis are intact; this remains a price-structure failure, and the framework does not average into one.'),

'ORCL': ('REPAIRING - STEP ONE OF THREE COMPLETE', 'IN ZONE + RECLAIMED SMA50 - GATE HOLDS', 'vd-caution',
 'Call Up - Sep 3, 2026 (CLOSEST YET): ORCL $145.75, down 4.9% but structurally improved. For the first time in months price sits ABOVE its SMA50 ($139.69), and it is inside the redrawn $138-150 zone. Both conditions are now partially met - which is further than ORCL has come since it broke down. THE GATE STILL HOLDS because the SMA50 is still FALLING. The sequence that repairs a broken trend is: reclaim the average, then the average flattens, then it rises. ORCL has completed step one of three. This is the name that validated the SMA gate in the first place by falling roughly 30% through its own zone, so the bar for re-entry is deliberately high and there is no reason to anticipate. WHAT TO WATCH: the SMA50 flattening. AI cloud RPO $553B and OCI +84% YoY mean the business case has never been the issue.'),

'AMD':  ('INTACT - ZONE DESIGN WORKING AS INTENDED', 'IN ZONE - BLOCKED BY DESIGN', 'vd-caution',
 'Call Up - Sep 3, 2026: AMD $457.06, down 5.4%, has entered the $440-470 zone - exactly as the Aug 13 redraw anticipated. That zone was set DELIBERATELY BENEATH the falling SMA50 so that a zone tag alone could not trigger an entry, and the design is now doing its job: SMA50 $501.70 is still falling with price $45 below it. AMD remains the large AI name furthest under its own trend filter, and it has now underperformed for two consecutive call ups (-2.6% then -5.4% while peers were mixed). ENTRY REQUIRES THE SMA50 RECLAIM, not merely the zone tag. MI400 Helios thesis unchanged - $60B committed from OpenAI and Meta, racks shipping - but a thesis without price confirmation is a watchlist item, not a trade.'),

'LMND': ('INTACT - KNIFE DECELERATING', 'IN ZONE 3RD TIME - GATE STILL BLOCKS', 'vd-caution',
 'Call Up - Sep 3, 2026: LMND $53.14, up 2.9% - inside zone $45-56 for the THIRD consecutive call up. The knife is decelerating: the stock has stopped falling and is basing sideways in the low $50s rather than making new lows. But SMA50 $58.83 is still falling and price is $5.69 beneath it, so the gate holds. THE TRIGGER IS UNCHANGED and has been stated the same way for three call ups: a base holding above $52 PLUS a flattening SMA50. LMND now has the first half and not the second. It is closer than it has been and still not actionable - and the consistency of that answer across three sessions is the framework working, not the framework being stubborn. Tesla FSD insurance live in AZ and OR; Q4 EBITDA target unchanged.'),

'MSFT': ('INTACT - ZONE CLOSING FROM BELOW', 'ABOVE ZONE - $497 HOLDING', 'vd-caution',
 'Call Up - Sep 3, 2026: MSFT $496.82, up 0.9%, holding its post-gap level through a pullback that took QQQ down 2.0%. The mechanically interesting development: SMA50 has climbed from $410.30 to $438.43 in three weeks and has now caught the TOP of the $410-438 zone. The zone is being closed from beneath by its own trend filter. That is a materially better structure than July, when the gate blocked MSFT at $394 with price sitting 20% above a falling average - any future pullback into this zone will arrive with the SMA50 right there, making it a clean test rather than a falling-knife catch. The Jul 30 Azure gap (+15.5% in one session) remains the single largest winner the SMA gate has cost, and the case for a pre-earnings exception still stands.'),

'NVDA': ('INTACT - QUIET RELATIVE STRENGTH', 'ABOVE ZONE - CLEANEST STRUCTURE', 'vd-caution',
 'Call Up - Sep 3, 2026: NVDA $224.41, essentially flat (+0.1%) through a pullback that took QQQ down 2.0% and IWM down 2.9%. Flat in a falling tape is quiet relative strength and worth logging. SMA50 $209.15 rising, SMA100 $203.20 below it, price above both - this remains the cleanest SMA structure on the watchlist. Zone $203-213 sits $11 below market. No entry: the setup is a pullback to the moving averages and the pullback that hit six other names did not reach NVDA. Blackwell GB300 ramp and $500B revenue visibility unchanged.'),

'PLTR': ('INTACT - EXTENSION RESOLVING THROUGH TIME', 'ABOVE ZONE - LESS EXTENDED', 'vd-caution',
 'Call Up - Sep 3, 2026: PLTR $169.46, down just 0.9% through the pullback despite carrying the "most extended name on the board" flag three weeks ago at 28% above its SMA50. The extension is resolving the healthy way: SMA50 has risen from $133.89 to $147.38 while price held flat, so the gap has narrowed to 15% through TIME rather than through a drawdown. That is what a strong trend digesting a run looks like. Zone $138-152 sits below market and the SMA50 is now inside it. Still no entry, but PLTR has moved from "do not chase" toward "watch for a routine pullback." 85% YoY revenue growth and the $7.65B FY2026 guide unchanged.'),

'DELL': ('WATCH - SMA50 HAS GONE FLAT', 'ABOVE ZONE - TREND FLATTENING', 'vd-caution',
 'Call Up - Sep 3, 2026 (CAUTION FLAG): DELL $492.20, up 1.6% and one of only three names higher over the pullback. But the trend filter has changed character: SMA50 $434.17 has gone FLAT after weeks of steep gains (it rose $434.10 to $434.22 to $434.17 across the last three sessions). THE AVGO LESSON FROM THIS SAME CALL UP APPLIES DIRECTLY - AVGO was flagged Aug 13 as the weakest gate pass precisely because its SMA50 was flat rather than rising, and it is now 11.7% lower and through its zone floor. A flat SMA50 is the absence of trend. DELL has not broken anything and price is comfortably above the average, but this moves it from unqualified gate pass to watch. Track whether the SMA50 turns up again or rolls over. AI server revenue +757% YoY and the $51.3B backlog are unchanged.'),
}

n=0
for tk,(th,vd,vc,al) in U.items():
    esc=lambda s: s.replace('\\','\\\\').replace("'","\\'")
    rep = ("    thesis:'"+esc(th)+"', verdict:'"+esc(vd)+"', verdictCls:'"+vc+"',\n"
           "    alert:'"+esc(al)+"',\n")
    pat = (r"(\n  "+tk+r": \{.*?)"
           r"\n    thesis:'(?:[^'\\]|\\.)*', verdict:'(?:[^'\\]|\\.)*', verdictCls:'[^']*',"
           r"\n    alert:'(?:[^'\\]|\\.)*',\n")
    src,k = re.subn(pat, lambda m: m.group(1)+"\n"+rep, src, flags=re.DOTALL)
    if k!=1: print(f'ERROR: {tk} matched {k}'); sys.exit(1)
    n+=1
open(FILE,'w').write(src); print(f'OK - {n} MONITOR_DATA entries refreshed'); os.remove(FILE+'.bak')
